name: Deep Agent Suite

on:
  schedule:
    - cron: '0 15 * * *'  # 10 AM EST (15:00 UTC)
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      Environment:
        description: "Which environment will be executed"
        required: true
        type: "choice"
        default: "prod"
        options: ["preprod", "staging", "stagingLatest", "prod"]
      tags:
        description: 'Test tag to run (without @)'
        required: false
        type: string

jobs:
  test:
    runs-on: windows-latest
    env:
      TEST_ENV: ${{ github.event.inputs.Environment || 'prod' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Debug - Environment Variables
        run: |
          echo "Selected Environment: $env:TEST_ENV"
        shell: pwsh

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps
        shell: pwsh

     - name: Run all tests
       if: github.event.inputs.tags == ''
       run: |
         npm run test
         echo "Test Exit Code: $?"
        EXIT_CODE=$?
        npm run report
        exit $EXIT_CODE
      env:
      CI: true
      TEST_ENV: ${{ env.TEST_ENV }}
      shell: bash

      - name: Run tests with specific tag
        if: github.event.inputs.tags != ''
        run: |
          npm run test:tag "@${{ github.event.inputs.tags }}"
          echo "Test Exit Code: $?"
          EXIT_CODE=$?
          npm run report
          exit $EXIT_CODE
       env:
       CI: true
       TEST_ENV: ${{ env.TEST_ENV }}
       shell: bash

      - name: Debug - List all files in reports folder
        run: |
          Write-Host "Listing all files in reports/"
          Get-ChildItem -Path reports -Recurse
        shell: pwsh

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.run_id }}-${{ env.TEST_ENV }}
          path: |
            reports/**
            cucumber-report.html
            cucumber-report.json
          retention-days: 30
          if-no-files-found: warn

      - name: Upload Playwright traces on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces-${{ github.run_id }}-${{ env.TEST_ENV }}
          path: |
            reports/traces/
            reports/screenshots/
          retention-days: 30
          if-no-files-found: ignore
